M48
; DRILL file KiCad 10.0.5 date 2026-08-03T18:12:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-03T18:12:58-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,MixedPlating,1,14
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X10.0Y-10.0
X10.0Y-290.0
X225.0Y-10.0
X225.0Y-290.0
X440.0Y-10.0
X440.0Y-290.0
M30
